version: "3.1"

services: 
    mi-sonarqube:
        container_name: mi-sonarqube
        image: sonarqube:8.6-community
        volumes:
            - /home/ubuntu/environment/datos/sonarqube/conf:/opt/sonarqube/conf
            - /home/ubuntu/environment/datos/sonarqube/data:/opt/sonarqube/data
            - /home/ubuntu/environment/datos/sonarqube/logs:/opt/sonarqube/logs
            - /home/ubuntu/environment/datos/sonarqube/extensions:/opt/sonarqube/extensions
        environment:
            SONAR_JDBC_PASSWORD: password
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_URL: jdbc:postgresql://mi-postgres:5432/sonar
        ports: 
            - 8080:9000
#######################################            
        ulimits:
            nofile:
                soft: 4096
                hard: 65536
    mi-postgres: # Identificador del servicio (por ahora, lo entendemos como el contenedor)
        container_name: mi-postgres # Nombre del contenedor
        image: postgres:latest
        environment:
            POSTGRES_PASSWORD: password
            POSTGRES_USER: sonar
            POSTGRES_DB: sonar
        volumes:
            - /home/ubuntu/environment/datos/sonarqube/postgre:/var/lib/postgresql/data
#        ports:
#            - 5432:5432
        restart: always
                